2022-02-25 20:52:39,648 ERROR Internal Server Error: /news/index/ C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('index.html'), <traceback object at 0x000002AF0287D680>)
Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\news_app\newapp\views.py", line 24, in get
    return HttpResponse(render(request, 'index.html', context))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
2022-02-25 20:52:39,654 ERROR "GET /news/index/ HTTP/1.1" 500 95278 C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\servers\basehttp.py None
2022-02-25 20:53:21,816 ERROR Internal Server Error: /news/index/ C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('index.html'), <traceback object at 0x000002AF02AD3400>)
Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\news_app\newapp\views.py", line 24, in get
    return HttpResponse(render(request, 'index.html', context))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
2022-02-25 20:53:21,821 ERROR "GET /news/index/ HTTP/1.1" 500 95415 C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\servers\basehttp.py None
2022-02-25 20:54:42,300 ERROR Internal Server Error: /news/index/ C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('index.html'), <traceback object at 0x000002AF02C098C0>)
Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\news_app\newapp\views.py", line 24, in get
    return HttpResponse(render(request, 'index.html', context))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
2022-02-25 20:54:42,304 ERROR "GET /news/index/ HTTP/1.1" 500 94821 C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\servers\basehttp.py None
2022-02-25 21:03:54,276 ERROR Internal Server Error: /news/ C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 65: 'get_available_languages', expected 'endcache'. Did you forget to register or load this tag?"), <traceback object at 0x0000022C903ADDC0>)
Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 500, in parse
    compile_func = self.tags[command]
KeyError: 'get_available_languages'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 176, in render
    return self._render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 130, in render
    compiled_parent = self.get_parent(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 127, in get_parent
    return self.find_template(parent, context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 106, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\engine.py", line 145, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 199, in compile_nodelist
    return parser.parse()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\templatetags\cache.py", line 78, in do_cache
    nodelist = parser.parse(('endcache',))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 502, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 552, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 65: 'get_available_languages', expected 'endcache'. Did you forget to register or load this tag?
2022-02-25 21:03:54,282 ERROR "GET /news/ HTTP/1.1" 500 205867 C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\servers\basehttp.py None
2022-02-25 21:04:09,161 ERROR Internal Server Error: /news/search/ C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Could not parse the remainder: '==' from 'language.code=='"), <traceback object at 0x0000022C9022A200>)
Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: 'language.code=='

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 176, in render
    return self._render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 130, in render
    compiled_parent = self.get_parent(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 127, in get_parent
    return self.find_template(parent, context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 106, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\engine.py", line 145, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 199, in compile_nodelist
    return parser.parse()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\templatetags\cache.py", line 78, in do_cache
    nodelist = parser.parse(('endcache',))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\defaulttags.py", line 810, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\defaulttags.py", line 904, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\defaulttags.py", line 837, in __init__
    super().__init__(*args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\defaulttags.py", line 840, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 593, in compile_filter
    return FilterExpression(token, self)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 692, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '==' from 'language.code=='
2022-02-25 21:04:09,169 ERROR "GET /news/search/ HTTP/1.1" 500 252611 C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\servers\basehttp.py None
2022-02-25 21:04:10,637 ERROR Internal Server Error: /news/add/ C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Could not parse the remainder: '==' from 'language.code=='"), <traceback object at 0x0000022C9028A500>)
Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: 'language.code=='

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 176, in render
    return self._render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 130, in render
    compiled_parent = self.get_parent(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 127, in get_parent
    return self.find_template(parent, context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 106, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\engine.py", line 145, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 199, in compile_nodelist
    return parser.parse()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\templatetags\cache.py", line 78, in do_cache
    nodelist = parser.parse(('endcache',))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\defaulttags.py", line 810, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\defaulttags.py", line 904, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\defaulttags.py", line 837, in __init__
    super().__init__(*args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\defaulttags.py", line 840, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 593, in compile_filter
    return FilterExpression(token, self)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 692, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '==' from 'language.code=='
2022-02-25 21:04:10,644 ERROR "GET /news/add/ HTTP/1.1" 500 241523 C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\servers\basehttp.py None
2022-02-25 21:04:19,297 ERROR Internal Server Error: /news/153/ C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Could not parse the remainder: '==' from 'language.code=='"), <traceback object at 0x0000022C90254880>)
Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: 'language.code=='

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 176, in render
    return self._render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 130, in render
    compiled_parent = self.get_parent(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 127, in get_parent
    return self.find_template(parent, context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 106, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\engine.py", line 145, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 199, in compile_nodelist
    return parser.parse()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\templatetags\cache.py", line 78, in do_cache
    nodelist = parser.parse(('endcache',))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\defaulttags.py", line 810, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\defaulttags.py", line 904, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\defaulttags.py", line 837, in __init__
    super().__init__(*args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\defaulttags.py", line 840, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 593, in compile_filter
    return FilterExpression(token, self)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 692, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '==' from 'language.code=='
2022-02-25 21:04:19,302 ERROR "GET /news/153/ HTTP/1.1" 500 242515 C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\servers\basehttp.py None
2022-02-25 21:04:22,299 ERROR Internal Server Error: /news/ C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Could not parse the remainder: '==' from 'language.code=='"), <traceback object at 0x0000022C901FA6C0>)
Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: 'language.code=='

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 176, in render
    return self._render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 130, in render
    compiled_parent = self.get_parent(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 127, in get_parent
    return self.find_template(parent, context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 106, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\engine.py", line 145, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 199, in compile_nodelist
    return parser.parse()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\templatetags\cache.py", line 78, in do_cache
    nodelist = parser.parse(('endcache',))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\defaulttags.py", line 810, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\defaulttags.py", line 904, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\defaulttags.py", line 837, in __init__
    super().__init__(*args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\defaulttags.py", line 840, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 593, in compile_filter
    return FilterExpression(token, self)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 692, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '==' from 'language.code=='
2022-02-25 21:04:22,306 ERROR "GET /news/ HTTP/1.1" 500 252637 C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\servers\basehttp.py None
2022-02-25 21:04:59,629 ERROR Internal Server Error: /news/ C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Could not parse the remainder: '==' from 'language.code=='"), <traceback object at 0x0000022C9028A940>)
Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: 'language.code=='

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 176, in render
    return self._render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 130, in render
    compiled_parent = self.get_parent(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 127, in get_parent
    return self.find_template(parent, context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 106, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\engine.py", line 145, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 199, in compile_nodelist
    return parser.parse()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\templatetags\cache.py", line 78, in do_cache
    nodelist = parser.parse(('endcache',))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\defaulttags.py", line 810, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\defaulttags.py", line 904, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\defaulttags.py", line 837, in __init__
    super().__init__(*args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\defaulttags.py", line 840, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 593, in compile_filter
    return FilterExpression(token, self)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 692, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '==' from 'language.code=='
2022-02-25 21:04:59,635 ERROR "GET /news/ HTTP/1.1" 500 252486 C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\servers\basehttp.py None
2022-02-25 21:16:52,400 ERROR Internal Server Error: /news/ C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Could not parse the remainder: '-=NewsPortal' from '-=NewsPortal'"), <traceback object at 0x0000022C90284980>)
Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 176, in render
    return self._render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 130, in render
    compiled_parent = self.get_parent(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 127, in get_parent
    return self.find_template(parent, context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 106, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\engine.py", line 145, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 199, in compile_nodelist
    return parser.parse()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\templatetags\cache.py", line 78, in do_cache
    nodelist = parser.parse(('endcache',))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\templatetags\i18n.py", line 379, in do_translate
    message_string = parser.compile_filter(bits[1])
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 593, in compile_filter
    return FilterExpression(token, self)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 692, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '-=NewsPortal' from '-=NewsPortal'
2022-02-25 21:16:52,406 ERROR "GET /news/ HTTP/1.1" 500 220275 C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\servers\basehttp.py None
2022-02-25 21:54:12,008 ERROR Internal Server Error: /news/ C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 9: 'trans', expected 'endblock'. Did you forget to register or load this tag?"), <traceback object at 0x00000264BC16B840>)
Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 500, in parse
    compile_func = self.tags[command]
KeyError: 'trans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\engine.py", line 163, in get_template
    template, origin = self.find_template(template_name)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\engine.py", line 145, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 199, in compile_nodelist
    return parser.parse()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 284, in do_extends
    nodelist = parser.parse()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 222, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 502, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 552, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 9: 'trans', expected 'endblock'. Did you forget to register or load this tag?
2022-02-25 21:54:12,018 ERROR "GET /news/ HTTP/1.1" 500 193821 C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\servers\basehttp.py None
2022-02-26 00:21:08,391 ERROR Internal Server Error: /admin/newapp/post/ C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: newapp_category.name_ru'), <traceback object at 0x000001DD06EF5340>)
Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 416, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: newapp_category.name_ru

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\contrib\admin\options.py", line 622, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\contrib\admin\sites.py", line 236, in inner
    return view(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\contrib\admin\options.py", line 1710, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\contrib\admin\options.py", line 742, in get_changelist_instance
    return ChangeList(
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\contrib\admin\views\main.py", line 100, in __init__
    self.queryset = self.get_queryset(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\contrib\admin\views\main.py", line 460, in get_queryset
    ) = self.get_filters(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\contrib\admin\views\main.py", line 160, in get_filters
    spec = field_list_filter_class(
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\contrib\admin\filters.py", line 159, in create
    return list_filter_class(field, request, params, model, model_admin, field_path=field_path)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\contrib\admin\filters.py", line 170, in __init__
    self.lookup_choices = self.field_choices(field, request, model_admin)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\contrib\admin\filters.py", line 207, in field_choices
    return field.get_choices(include_blank=False, ordering=ordering)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\fields\__init__.py", line 882, in get_choices
    return (blank_choice if include_blank else []) + [
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\query.py", line 280, in __iter__
    self._fetch_all()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\query.py", line 1354, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1202, in execute_sql
    cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 416, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: newapp_category.name_ru
2022-02-26 00:21:08,403 ERROR "GET /admin/newapp/post/ HTTP/1.1" 500 199260 C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\servers\basehttp.py None
2022-02-26 00:21:19,054 ERROR Internal Server Error: /admin/newapp/category/ C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: newapp_category.name_ru'), <traceback object at 0x000001DD07132380>)
Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 416, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: newapp_category.name_ru

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\contrib\admin\options.py", line 622, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\contrib\admin\sites.py", line 236, in inner
    return view(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\contrib\admin\options.py", line 1828, in changelist_view
    'selection_note': _('0 of %(cnt)s selected') % {'cnt': len(cl.result_list)},
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\query.py", line 1354, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1202, in execute_sql
    cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 416, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: newapp_category.name_ru
2022-02-26 00:21:19,058 ERROR "GET /admin/newapp/category/ HTTP/1.1" 500 159717 C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\servers\basehttp.py None
2022-02-26 00:21:25,793 ERROR Internal Server Error: /admin/newapp/category/ C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: newapp_category.name_ru'), <traceback object at 0x000001DD0700A340>)
Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 416, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: newapp_category.name_ru

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\contrib\admin\options.py", line 622, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\contrib\admin\sites.py", line 236, in inner
    return view(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\contrib\admin\options.py", line 1828, in changelist_view
    'selection_note': _('0 of %(cnt)s selected') % {'cnt': len(cl.result_list)},
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\query.py", line 1354, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1202, in execute_sql
    cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 416, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: newapp_category.name_ru
2022-02-26 00:21:25,798 ERROR "GET /admin/newapp/category/ HTTP/1.1" 500 159716 C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\servers\basehttp.py None
2022-02-26 00:22:49,421 ERROR Internal Server Error: /admin/newapp/category/ C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: newapp_category.name_ru'), <traceback object at 0x000002305DA1C640>)
Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 416, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: newapp_category.name_ru

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\contrib\admin\options.py", line 622, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\contrib\admin\sites.py", line 236, in inner
    return view(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\contrib\admin\options.py", line 1828, in changelist_view
    'selection_note': _('0 of %(cnt)s selected') % {'cnt': len(cl.result_list)},
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\query.py", line 1354, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1202, in execute_sql
    cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 416, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: newapp_category.name_ru
2022-02-26 00:22:49,434 ERROR "GET /admin/newapp/category/ HTTP/1.1" 500 159853 C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\servers\basehttp.py None
2022-02-26 00:23:25,579 ERROR Internal Server Error: /news/ C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: newapp_post.title_ru'), <traceback object at 0x000002BBFD706280>)
Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 416, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: newapp_post.title_ru

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 176, in render
    return self._render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 153, in render
    return compiled_parent._render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\defaulttags.py", line 171, in render
    len_values = len(values)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\query.py", line 1354, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1202, in execute_sql
    cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 416, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: newapp_post.title_ru
2022-02-26 00:23:25,590 ERROR "GET /news/ HTTP/1.1" 500 206961 C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\servers\basehttp.py None
2022-02-26 00:25:21,817 ERROR Internal Server Error: /news/ C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: newapp_post.title_ru'), <traceback object at 0x000001D58232AB40>)
Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 416, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: newapp_post.title_ru

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 176, in render
    return self._render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 153, in render
    return compiled_parent._render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\defaulttags.py", line 171, in render
    len_values = len(values)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\query.py", line 1354, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1202, in execute_sql
    cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 416, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: newapp_post.title_ru
2022-02-26 00:25:21,827 ERROR "GET /news/ HTTP/1.1" 500 206961 C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\servers\basehttp.py None
2022-02-26 00:25:40,270 ERROR Internal Server Error: /news/ C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: newapp_post.title_ru'), <traceback object at 0x000001D582599A40>)
Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 416, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: newapp_post.title_ru

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 176, in render
    return self._render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 153, in render
    return compiled_parent._render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\defaulttags.py", line 171, in render
    len_values = len(values)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\query.py", line 1354, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1202, in execute_sql
    cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 416, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: newapp_post.title_ru
2022-02-26 00:25:40,276 ERROR "GET /news/ HTTP/1.1" 500 206961 C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\servers\basehttp.py None
2022-02-26 00:35:23,515 ERROR Internal Server Error: /news/ C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: newapp_post.title_ru'), <traceback object at 0x000001A7AA517A00>)
Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 416, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: newapp_post.title_ru

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 176, in render
    return self._render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 153, in render
    return compiled_parent._render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\defaulttags.py", line 171, in render
    len_values = len(values)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\query.py", line 1354, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1202, in execute_sql
    cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 416, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: newapp_post.title_ru
2022-02-26 00:35:23,533 ERROR "GET /news/ HTTP/1.1" 500 206961 C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\servers\basehttp.py None
2022-02-26 10:54:46,128 ERROR Internal Server Error: /news/index/ C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Could not parse the remainder: '==' from 'language.code=='"), <traceback object at 0x000001E9974F36C0>)
Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: 'language.code=='

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\news_app\newapp\views.py", line 33, in get
    return HttpResponse(render(request, 'index.html', context))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 176, in render
    return self._render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 130, in render
    compiled_parent = self.get_parent(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 127, in get_parent
    return self.find_template(parent, context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 106, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\engine.py", line 145, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 199, in compile_nodelist
    return parser.parse()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\templatetags\cache.py", line 78, in do_cache
    nodelist = parser.parse(('endcache',))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\defaulttags.py", line 810, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\defaulttags.py", line 904, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\defaulttags.py", line 837, in __init__
    super().__init__(*args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\defaulttags.py", line 840, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 593, in compile_filter
    return FilterExpression(token, self)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 692, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '==' from 'language.code=='
2022-02-26 10:54:46,137 ERROR "GET /news/index/ HTTP/1.1" 500 327138 C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\servers\basehttp.py None
2022-02-26 11:07:36,895 ERROR Internal Server Error: / C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 13: 'get_current_timezone', expected 'endblock'. Did you forget to register or load this tag?"), <traceback object at 0x000001E9974A9400>)
Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 500, in parse
    compile_func = self.tags[command]
KeyError: 'get_current_timezone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\engine.py", line 163, in get_template
    template, origin = self.find_template(template_name)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\engine.py", line 145, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 199, in compile_nodelist
    return parser.parse()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 284, in do_extends
    nodelist = parser.parse()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 222, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 502, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 552, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 13: 'get_current_timezone', expected 'endblock'. Did you forget to register or load this tag?
2022-02-26 11:07:36,900 ERROR "GET / HTTP/1.1" 500 184803 C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\servers\basehttp.py None
2022-02-26 11:08:08,247 ERROR Internal Server Error: / C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError('<ExtendsNode: extends "main.html"> must be the first tag in the template.'), <traceback object at 0x000001E997638C00>)
Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\engine.py", line 163, in get_template
    template, origin = self.find_template(template_name)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\engine.py", line 145, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 199, in compile_nodelist
    return parser.parse()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 509, in parse
    self.extend_nodelist(nodelist, compiled_result, token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 526, in extend_nodelist
    raise self.error(
django.template.exceptions.TemplateSyntaxError: <ExtendsNode: extends "main.html"> must be the first tag in the template.
2022-02-26 11:08:08,251 ERROR "GET / HTTP/1.1" 500 135016 C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\servers\basehttp.py None
2022-02-26 11:09:29,845 ERROR Internal Server Error: /news/index/ C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 85: 'get_current_timezone', expected 'endcache'. Did you forget to register or load this tag?"), <traceback object at 0x000001E997521740>)
Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 500, in parse
    compile_func = self.tags[command]
KeyError: 'get_current_timezone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\news_app\newapp\views.py", line 33, in get
    return HttpResponse(render(request, 'index.html', context))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 176, in render
    return self._render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 130, in render
    compiled_parent = self.get_parent(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 127, in get_parent
    return self.find_template(parent, context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 106, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\engine.py", line 145, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 199, in compile_nodelist
    return parser.parse()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\templatetags\cache.py", line 78, in do_cache
    nodelist = parser.parse(('endcache',))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 502, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 552, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 85: 'get_current_timezone', expected 'endcache'. Did you forget to register or load this tag?
2022-02-26 11:09:29,850 ERROR "GET /news/index/ HTTP/1.1" 500 282502 C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\servers\basehttp.py None
2022-02-26 11:10:00,686 ERROR Internal Server Error: /news/index/ C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 83: 'get_current_timezone', expected 'endcache'. Did you forget to register or load this tag?"), <traceback object at 0x000001E997548580>)
Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 500, in parse
    compile_func = self.tags[command]
KeyError: 'get_current_timezone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\news_app\newapp\views.py", line 33, in get
    return HttpResponse(render(request, 'index.html', context))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 176, in render
    return self._render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 130, in render
    compiled_parent = self.get_parent(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 127, in get_parent
    return self.find_template(parent, context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 106, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\engine.py", line 145, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 199, in compile_nodelist
    return parser.parse()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\templatetags\cache.py", line 78, in do_cache
    nodelist = parser.parse(('endcache',))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 502, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 552, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 83: 'get_current_timezone', expected 'endcache'. Did you forget to register or load this tag?
2022-02-26 11:10:00,692 ERROR "GET /news/index/ HTTP/1.1" 500 280516 C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\servers\basehttp.py None
2022-02-26 11:10:04,783 ERROR Internal Server Error: /news/ C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 83: 'get_current_timezone', expected 'endcache'. Did you forget to register or load this tag?"), <traceback object at 0x000001E9976937C0>)
Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 500, in parse
    compile_func = self.tags[command]
KeyError: 'get_current_timezone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 176, in render
    return self._render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 130, in render
    compiled_parent = self.get_parent(context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 127, in get_parent
    return self.find_template(parent, context)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader_tags.py", line 106, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\engine.py", line 145, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 199, in compile_nodelist
    return parser.parse()
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\templatetags\cache.py", line 78, in do_cache
    nodelist = parser.parse(('endcache',))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 502, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\base.py", line 552, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 83: 'get_current_timezone', expected 'endcache'. Did you forget to register or load this tag?
2022-02-26 11:10:04,790 ERROR "GET /news/ HTTP/1.1" 500 213270 C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\servers\basehttp.py None
